#  IRIS Source Code
#  Copyright (C) 2026 - DFIR-IRIS
#  contact@dfir-iris.org
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 3 of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

"""v2 endpoints supporting the Access Control admin page.

Two small concerns:

  * `GET /schema` — exposes the `Permissions` (bitmask) and
    `CaseAccessLevel` enums + their canonical labels. The frontend
    renders the permission editor + the case-access dropdown
    directly from this so adding a new permission bit or access
    level only needs a backend change.
  * `GET /accessible-cases` — server-side scoped case picker for
    the per-user / per-group case-access modals. Returns at most
    200 rows, ordered newest-first, filtered by an optional `search`
    ILIKE on case name + SOC id. Each row is re-checked against the
    current user's case ACL — even though the page is admin-gated,
    an admin who's removed themselves from a case still doesn't see
    it.
  * `POST /recompute-all` — wrapper around the existing
    `ac_recompute_all_users_effective_ac()` helper so admins can
    rebuild the effective-access cache from the UI after a manual
    DB poke.
"""

from typing import Any
from typing import Dict
from typing import List

from flask import Blueprint
from flask import Response
from flask import request

from app.blueprints.access_controls import ac_api_requires
from app.blueprints.access_controls import ac_fast_check_current_user_has_case_access
from app.blueprints.rest.endpoints import response_api_success
from app.iris_engine.access_control.utils import ac_recompute_all_users_effective_ac
from app.models.authorization import CaseAccessLevel
from app.models.authorization import Permissions
from app.models.cases import Cases


access_control_blueprint = Blueprint(
    'access_control_rest_v2', __name__, url_prefix='/access-control'
)


# Human-readable labels + short descriptions for each permission bit.
# Keyed by enum name. Strictly additive — adding a new permission to
# `app.models.authorization.Permissions` will surface in the response
# even without a label here; the UI falls back to the enum name.
_PERMISSION_LABELS: Dict[str, Dict[str, str]] = {
    'standard_user': {
        'label': 'Standard user',
        'description': 'Bare minimum required to log in. Always implicitly set.',
    },
    'server_administrator': {
        'label': 'Server administrator',
        'description': 'Full administrative access. Take care assigning this.',
    },
    'alerts_read': {
        'label': 'Read alerts',
        'description': 'View the alerts queue.',
    },
    'alerts_write': {
        'label': 'Write alerts',
        'description': 'Triage, edit and escalate alerts.',
    },
    'alerts_delete': {
        'label': 'Delete alerts',
        'description': 'Permanently delete alerts.',
    },
    'search_across_cases': {
        'label': 'Search across cases',
        'description': 'Global search reaches every case (subject to per-case access).',
    },
    'customers_read': {
        'label': 'Read customers',
        'description': 'View the customer directory.',
    },
    'customers_write': {
        'label': 'Write customers',
        'description': 'Create, edit and delete customer records.',
    },
    'case_templates_read': {
        'label': 'Read case templates',
        'description': 'View the case template library.',
    },
    'case_templates_write': {
        'label': 'Write case templates',
        'description': 'Create, edit and delete case templates.',
    },
    'activities_read': {
        'label': 'Read own activities',
        'description': "View activity entries the user generated.",
    },
    'all_activities_read': {
        'label': 'Read all activities',
        'description': 'View activity entries generated by every user.',
    },
}

_CASE_ACCESS_LABELS: Dict[str, Dict[str, str]] = {
    'deny_all': {
        'label': 'Deny all',
        'description': 'Explicitly refuse access (overrides group / org grants).',
    },
    'read_only': {
        'label': 'Read only',
        'description': 'View the case and its objects without editing.',
    },
    'full_access': {
        'label': 'Full access',
        'description': 'View, edit and add objects to the case.',
    },
}


@access_control_blueprint.get('/schema')
@ac_api_requires(Permissions.server_administrator)
def get_access_control_schema() -> Response:
    """Enum metadata for the Access Control editor.

    Permissions are exposed as a flat list of `{name, value, label,
    description}` ordered by their bit value — that's the order the
    editor renders the checklist. CaseAccessLevel is shipped the
    same way but as a small mutually-exclusive set the UI renders as
    a select.
    """
    perms = []
    for perm in sorted(Permissions, key=lambda p: p.value):
        meta = _PERMISSION_LABELS.get(perm.name, {})
        perms.append({
            'name': perm.name,
            'value': perm.value,
            'label': meta.get('label', perm.name.replace('_', ' ').capitalize()),
            'description': meta.get('description', ''),
        })

    access_levels = []
    for level in sorted(CaseAccessLevel, key=lambda l: l.value):
        meta = _CASE_ACCESS_LABELS.get(level.name, {})
        access_levels.append({
            'name': level.name,
            'value': level.value,
            'label': meta.get('label', level.name.replace('_', ' ').capitalize()),
            'description': meta.get('description', ''),
        })

    return response_api_success({
        'permissions': perms,
        'case_access_levels': access_levels,
    })


@access_control_blueprint.get('/accessible-cases')
@ac_api_requires(Permissions.server_administrator)
def list_accessible_cases() -> Response:
    """Lightweight case picker for the per-user / per-group case-access
    modals.

    Returns at most 200 rows ordered by `case_id DESC`, optionally
    filtered by a `search` ILIKE on case name + SOC id. Each
    candidate is re-checked with `ac_fast_check_current_user_has_case_access`
    so an admin who's explicitly removed themselves from a case
    still doesn't see it in the picker.
    """
    from sqlalchemy import or_
    query = Cases.query.with_entities(Cases.case_id, Cases.name, Cases.soc_id)
    search = (request.args.get('search') or '').strip() or None
    if search:
        needle = f'%{search}%'
        query = query.filter(or_(Cases.name.ilike(needle), Cases.soc_id.ilike(needle)))
    query = query.order_by(Cases.case_id.desc()).limit(200)

    items: List[Dict[str, Any]] = []
    for row in query.all():
        if not ac_fast_check_current_user_has_case_access(
            row.case_id, [CaseAccessLevel.read_only, CaseAccessLevel.full_access]
        ):
            continue
        items.append({
            'case_id': row.case_id,
            'name': row.name,
            'soc_id': row.soc_id,
        })

    return response_api_success({'data': items})


@access_control_blueprint.post('/recompute-all')
@ac_api_requires(Permissions.server_administrator)
def recompute_all_users_access() -> Response:
    """Rebuild the effective-access cache for every user.

    Expensive on large fleets — the legacy UI gated this behind a
    confirmation. The page does the same client-side; the endpoint
    itself just runs the helper synchronously.
    """
    ac_recompute_all_users_effective_ac()
    return response_api_success({'message': 'Recomputed effective access for all users'})
